# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 24 May 2021 09:37:10 +0000
*               @ALL          0
*               @user         8
