<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: sa
 * Date: Mon, 24 May 2021 09:46:07 +0000
 */

$conf['title'] = 'wiki';
$conf['lang'] = 'ru';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['renderer_xhtml'] = 'xbr';
