# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Mon, 24 May 2021 09:37:10 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

sa:$2y$10$bgBYrJIaRvxTGYbmyo1rP.d2S5DLO27AV3WDthP9R0HIeBzgO7HeK:Храпов Роман Васильевич:hardrom@gmail.com:admin,user
