# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Mon, 24 May 2021 09:37:10 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

krv:$2y$10$8cnNz8KJEHHz5LU7bXdWmefAmwyirgZbL6v1dBzoGUBM.KssXQm8y:Khrapov Roman:hardrom@gmail.com:user
sa:$2y$10$cu82B2Bu37wNL5BQzb6vKeHBFBF6/zxu/0IkvNreR5BHJiS76OIoW:Храпов Роман Васильевич:hardrom@gmail.com:admin,user
vsk:$2y$10$HOFvK5YOkE6cOIDZCXnROunOCVGTRkp1pNwJyqEuVaw6TvpOqgfRK:Viktor:1@mail.ru:user
